defaults: &defaults
  omniauth_path_prefix: "/auth"
  site_domain: "http://localhost:3000/"
  site_name: "SwapArt"
  author: "Andrei Averkin"
  meta_description: "Swap art with people like you"
  meta_keywords: "swap, art, free, network"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  site_name: "SwapArt - development"
  site_domain: "http://shielded-everglades-2939.herokuapp.com/"
