defaults: &defaults
  secret_key_base: 6fa60ece08e5445c059084712dee02fbee926f46ca417a85c6eb912d98196f096cd63d29728fbafb146468fa973f9e8ae0f1b15ab411b25a7cf4277283c5e9b6
  email_user: notification@swapart.co
  email_pass: ssar5248
  facebook_APP_ID: 709901159065153
  facebook_APP_SECRET: 186254b8e75c3b16f576703b13b35e18
  admin_pass: averkinswap

  AWS_ACCESS_KEY_ID: AKIA##DELME##JQWE7T7APR7BYWFQ##METOO##
  AWS_SECRET_ACCESS_KEY: zvTJp##DELME##IguhfEi9AaVrn36mSmCU0CzbDcXADJ5Xebj##METOO##

development:
  <<: *defaults
  S3_BUCKET_NAME: swapart-development

test:
  <<: *defaults
  S3_BUCKET_NAME: swapart-test

production:
  <<: *defaults
  facebook_APP_ID: 709900169065252
  facebook_APP_SECRET: 2b2159f4bd9e8b8400d071064777297c
  S3_BUCKET_NAME: swapart
