require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SwapsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Swap. As you add validations to Swap, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SwapsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all swaps as @swaps" do
      swap = Swap.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:swaps)).to eq([swap])
    end
  end

  describe "GET show" do
    it "assigns the requested swap as @swap" do
      swap = Swap.create! valid_attributes
      get :show, {:id => swap.to_param}, valid_session
      expect(assigns(:swap)).to eq(swap)
    end
  end

  describe "GET new" do
    it "assigns a new swap as @swap" do
      get :new, {}, valid_session
      expect(assigns(:swap)).to be_a_new(Swap)
    end
  end

  describe "GET edit" do
    it "assigns the requested swap as @swap" do
      swap = Swap.create! valid_attributes
      get :edit, {:id => swap.to_param}, valid_session
      expect(assigns(:swap)).to eq(swap)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Swap" do
        expect {
          post :create, {:swap => valid_attributes}, valid_session
        }.to change(Swap, :count).by(1)
      end

      it "assigns a newly created swap as @swap" do
        post :create, {:swap => valid_attributes}, valid_session
        expect(assigns(:swap)).to be_a(Swap)
        expect(assigns(:swap)).to be_persisted
      end

      it "redirects to the created swap" do
        post :create, {:swap => valid_attributes}, valid_session
        expect(response).to redirect_to(Swap.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved swap as @swap" do
        post :create, {:swap => invalid_attributes}, valid_session
        expect(assigns(:swap)).to be_a_new(Swap)
      end

      it "re-renders the 'new' template" do
        post :create, {:swap => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested swap" do
        swap = Swap.create! valid_attributes
        put :update, {:id => swap.to_param, :swap => new_attributes}, valid_session
        swap.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested swap as @swap" do
        swap = Swap.create! valid_attributes
        put :update, {:id => swap.to_param, :swap => valid_attributes}, valid_session
        expect(assigns(:swap)).to eq(swap)
      end

      it "redirects to the swap" do
        swap = Swap.create! valid_attributes
        put :update, {:id => swap.to_param, :swap => valid_attributes}, valid_session
        expect(response).to redirect_to(swap)
      end
    end

    describe "with invalid params" do
      it "assigns the swap as @swap" do
        swap = Swap.create! valid_attributes
        put :update, {:id => swap.to_param, :swap => invalid_attributes}, valid_session
        expect(assigns(:swap)).to eq(swap)
      end

      it "re-renders the 'edit' template" do
        swap = Swap.create! valid_attributes
        put :update, {:id => swap.to_param, :swap => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested swap" do
      swap = Swap.create! valid_attributes
      expect {
        delete :destroy, {:id => swap.to_param}, valid_session
      }.to change(Swap, :count).by(-1)
    end

    it "redirects to the swaps list" do
      swap = Swap.create! valid_attributes
      delete :destroy, {:id => swap.to_param}, valid_session
      expect(response).to redirect_to(swaps_url)
    end
  end

end
